const agora = new Date().getMonth() // +1 pq é um array e ele entende como indice
const hoje = new Date()
const mesPorExtenso = hoje.toLocaleString('pt-BR', { month: 'long' })
const diaPorExtenso = hoje.toLocaleString('pt-BR', { weekday: 'long' })
console.log(`Mês por extenso: ${mesPorExtenso}`)
// console.log(`Mês atual: ${agora}`)
console.clear()
console.log(`Dia da semana por extenso: ${diaPorExtenso}`)
console.log(hoje.getHours())
console.log(hoje.getMinutes())
console.log(hoje.getUTCDay())
console.log(hoje.getSeconds())
console.log(hoje.getFullYear())
console.log(hoje.getTime())
